name: 🧪 Run Build Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build JF Web
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - run: npm install --global yarn
    - run: npm install gulp-cli
    - run: yarn install
    - run: yarn build:production
    
    - name: Check Build
      run: test -d dist

    - name: Rename dist
      run: mv dist jellyfin-web

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: jellyfin-web
        path: jellyfin-web
