name: 🧪 Run Build Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build JF Web
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build-config:
          - production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --no-audit
        env:
          SKIP_PREPARE: true

      - name: Build
        run: npm run build:${{ matrix.build-config }}

      - name: Check Build
        run: test -d dist

      - name: Rename dist
        run: mv dist jellyfin-web

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jellyfin-web
          path: jellyfin-web
